spring:
  application:
    name: reactive-lambda
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
  cloud:
    function:
      definition: hello

aws:
  region: ${AWS_REGION:us-east-1}

logging:
  pattern:
    json: true
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.cloud.function: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always



